apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo
  labels: # these labels are deployment labels
    app: backend
    project: mern-todo
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: backend
      project: mern-todo
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: backend
        project: mern-todo
        tier: app
    spec:
      containers:
      - name: backend
        image: localhost:30001/todoapp-backend:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: backend