apiVersion: v1
kind: Service
metadata:
  name: node-api
  namespace: todo
spec:
  selector:
    app: backend
    project: mern-todo
    tier: app
  ports:
  - protocol: TCP
    port: 5000 #service-port
    targetPort: 5000 #container-port