version: "3"

services:

  backend:
    build: ./backend
    container_name: node-api
    restart: always
    env_file:
      - mongodb.env
    networks:
      - mern-networks
  
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge