services:

  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mern-networks

  backend:
    build: ./backend
    container_name: node-api
    restart: always
    env_file:
      - mongodb.env
    networks:
      - mern-networks
  
   # React Frontend Service
  frontend:
    build: ./frontend
    container_name: web
    depends_on:
      - backend
    networks:
      - mern-networks

  # NGINX Service as reverse proxy
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge