version: "3"

services:

  database:
    image: mongo
    container_name: mongodb
    networks:
      - mern-networks
  
  backend:
    build: ./backend
    container_name: node-api
    restart: always
    environment:
      MONGO_URI: "mongodb://mongodb:27017/ToDoAppDb"
    depends_on:
      - database
    networks:
      - mern-networks
  
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge