apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: todo
spec:
  type: LoadBalancer
  selector:
    app: frontend
    project: mern-todo
    tier: web
  ports:
  - protocol: TCP
    port: 80 # service-port
    targetPort: 3000 # container-port